global using LearnHub_Api.Consts;
global using LearnHub_Api.Contracts.Authentication;
global using LearnHub_Api.Entities;
global using Microsoft.AspNetCore.Identity;
global using static LearnHub_Api.Errors.UserErrors;
global using Microsoft.AspNetCore.Authorization;
global using FluentValidation;
global using LearnHub_Api.Persistence;
global using LearnHub_Api.Services;
global using Microsoft.EntityFrameworkCore;
global using System.Reflection;
global using Mapster;
global using MapsterMapper;
